CREATE TABLE "Users" (
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	Hash UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	Username VARCHAR(120) NOT NULL,
	Password VARCHAR(120) NOT NULL,
	EMail VARCHAR(50),
	CompanyId BIGINT NOT NULL
);