CREATE TABLE RefreshTokens(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	Token VARCHAR(120) NOT NULL,
	ExpireDate DATETIME NOT NULL,
	IsUsed BIT NOT NULL DEFAULT 0,
	CreatedBy VARCHAR(15) NOT NULL,
	ReplacedByToken VARCHAR(120) NULL,
	UsedBy VARCHAR(15) NULL,
	UserId BIGINT NOT NULL,
);