CREATE TABLE UserRoles(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	UserId BIGINT FOREIGN KEY REFERENCES "Users"(Id),
	RoleId BIGINT FOREIGN KEY REFERENCES "Roles"(Id)
);