CREATE TABLE Company(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	Hash UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(15),
	Email VARCHAR(50)
);