CREATE TABLE "Location"(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	Hash UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	City VARCHAR(100) NOT NULL,
	PostalCode VARCHAR(10) NOT NULL,
	Street VARCHAR(100) NOT NULL,
	No VARCHAR(16) NOT NULL,
	PhoneNumber VARCHAR(15),
	Email VARCHAR(15),
	CompanyId BIGINT FOREIGN KEY REFERENCES Company(Id)
);