CREATE TABLE "RolePermissions"(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	RoleId BIGINT FOREIGN KEY REFERENCES Roles("Id"),
	PermissionToId BIGINT FOREIGN KEY REFERENCES PermissionToEnum("Id"),
	PermissionActionId BIGINT FOREIGN KEY REFERENCES PermissionActionEnum("Id")
);