CREATE TABLE "Logs" (
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	LogType INT NOT NULL,
	Message TEXT NOT NULL,
	InnerException TEXT,
	StackTrace TEXT
);