CREATE TABLE PasswordRecovery(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateTime DATETIME,
	Hash UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	UserId BIGINT FOREIGN KEY REFERENCES "Users"(Id) ON DELETE NO ACTION
);